[workspace]
resolver = "2"

members = [
  "chokan-dic",
  "skk-notes-converter",
  "libs/dic",
  "libs/kkc",
  "libs/trie"
, "chokan-server", "skk-tankan-converter", "skk-dic-parser", "skk-noun-converter"]
