# https://taskfile.dev

version: '3'

vars:
  EMACS_BATCH: emacs -Q --batch -L .

tasks:
   
  build:
    sources:
      - './*.el'

    generates:
      - './*.elc'
    cmds:
      - for: sources
        cmd: '{{ .EMACS_BATCH }} -f batch-byte-compile {{ .ITEM }}'

  test:
    deps: [build]
    cmds:
      - '{{ .EMACS_BATCH }} -l chokan-tests.el -l ert --eval "(ert-run-tests-batch-and-exit)"'
  clean:
    cmds:
      - find . -type f -name "*.elc" | xargs rm

  make-notes-dic:
    dir: skk-notes-converter
    cmds:
      - sh make-jisyo.sh
  make-tankan-dic:
    dir: skk-tankan-converter
    cmds:
      - sh make-jisyo.sh
  make-dic:
    deps: [make-notes-dic, make-tankan-dic]
    dir: chokan-dic
    cmds:
      - cargo run --bin chokan-dic -- ../skk-notes-converter/dic/chokan.notes.dic ./dict/huzoku.dic ../skk-tankan-converter/dic/chokan.tankan.dic dictionary.dat
