# https://taskfile.dev

version: '3'

vars:
  EMACS_BATCH: emacs -Q --batch -L .

tasks:
   
  build:
    sources:
      - './chokan.el'
    generates:
      - './chokan.elc'
    cmds:
      - for: sources
        cmd: '{{ .EMACS_BATCH }} -f batch-byte-compile {{ .ITEM }}'

  test:
    deps: [build]
    cmds:
      - '{{ .EMACS_BATCH }} -l chokan-tests.el -l ert --eval "(ert-run-tests-batch-and-exit)"'
  clean:
    cmds:
      - find . -type f -name "*.elc" | xargs rm

  make-notes-dic:
    dir: skk-notes-converter
    cmds:
      - sh make-jisyo.sh
  make-tankan-dic:
    dir: skk-tankan-converter
    cmds:
      - sh make-jisyo.sh
  make-noun-dic:
    dir: skk-noun-converter
    cmds:
      - sh make-jisyo.sh
  make-jinmei-dic:
    dir: skk-jinmei-converter
    cmds:
      - sh make-jisyo.sh
  make-dic:
    deps: [make-notes-dic, make-tankan-dic, make-noun-dic, make-jinmei-dic]
    dir: chokan-dic
    cmds:
      - mkdir -p work
      - cat ./dict/huzoku.dic ../skk-notes-converter/dic/chokan.huzoku.dic > work/huzoku.dic
      - cat ../skk-notes-converter/dic/chokan.notes.dic ../skk-noun-converter/dic/chokan.noun.dic ../skk-jinmei-converter/dic/chokan.jinmei.dic ./dict/standard.dic > work/standard.dic
      - cargo run --bin chokan-dic -- ./work/standard.dic ./work/huzoku.dic ../skk-tankan-converter/dic/chokan.tankan.dic dictionary.dat
    env:
      RUST_LOG: info
