[package]
name = "skk-notes-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dic = { version = "0.1.0", path = "../dic" }
peg = "0.8.2"
