[package]
name = "skk-jinmei-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
dic = { version = "0.1.0", path = "../libs/dic" }
encoding_rs = "0.8.34"
encoding_rs_io = "0.1.7"
peg = "0.8.3"
skk-dic-parser = { version = "0.1.0", path = "../skk-dic-parser" }
